# Helm v3.0.0
# Kubernetes v1.24.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "task-service.labels" . | nindent 4 }}
  annotations:
    # Prometheus monitoring configuration
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8083"
    
    # AWS Load Balancer configurations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "30"
    
    # Additional service annotations from values
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    # Main application port
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    
    # Metrics port for monitoring
    - port: 8083
      targetPort: http
      protocol: TCP
      name: metrics

  # Pod selector using template helper
  selector:
    {{- include "task-service.selectorLabels" . | nindent 4 }}
  
  # Session affinity configuration for consistent routing
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hour timeout for session stickiness
  
  # Ensure service is published to service mesh
  publishNotReadyAddresses: false
  
  # Configure health check
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort | default 0 }}
  
  # External traffic policy for better routing
  externalTrafficPolicy: Local
  
  # Configure IP family policy
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4