apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: task-management
    monitoring.enabled: {{ .Values.service.monitoring.enabled | quote }}
  annotations:
    prometheus.io/scrape: {{ .Values.service.monitoring.enabled | quote }}
    prometheus.io/port: {{ .Values.service.monitoring.port | quote }}
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
    - port: {{ .Values.service.monitoring.port }}
      targetPort: {{ .Values.service.monitoring.port }}
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "auth-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  publishNotReadyAddresses: false
  externalTrafficPolicy: Local