# Default values for project-service Helm chart
# This is a YAML-formatted file.

# Bitnami Common Chart Version: ^2.0.0

# Override name of the release
nameOverride: ""
# Override the full name of the release
fullnameOverride: ""

# Container image configuration
image:
  repository: taskmanager/project-service
  tag: 1.0.0
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  # Number of replicas for high availability
  replicaCount: 3
  
  # Deployment strategy configuration
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  # Pod annotations for Prometheus monitoring
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
  
  # Resource limits and requests for performance optimization
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  # Liveness probe configuration
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  # Readiness probe configuration
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  # Node selector configuration
  nodeSelector: {}
  
  # Pod anti-affinity for high availability
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: project-service
            topologyKey: kubernetes.io/hostname
  
  # Pod tolerations
  tolerations: []

# Service configuration
service:
  type: ClusterIP
  port: 8082
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"

# Enhanced pod security context
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  supplementalGroups:
    - 1000

# Enhanced container security context
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
    type: RuntimeDefault

# Production environment variables
env:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8082"
  MANAGEMENT_SERVER_PORT: "8082"
  JAVA_OPTS: "-Xms1G -Xmx2G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8"
  SPRING_SECURITY_REQUIRE_SSL: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,prometheus,info"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"